# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Species_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('Family', models.CharField(max_length=100)),
                ('Scientific_Name', models.CharField(max_length=100)),
                ('Synonym', models.CharField(max_length=100)),
                ('Vernacular_name', models.CharField(max_length=100)),
                ('Species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plant_list.Plants')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_list.Plants'),
        ),
    ]
